version: '2.1'

services:

  myappname:
    container_name: myappname
    build:
      context: .
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
    volumes:
      - './src:/usr/src/app/src'
    ports:
      - '9000:3000' # expose ports - HOST:CONTAINER
